require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec # or rubocop-minitest

AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "bin/**/*"

Layout/LineLength:
  Max: 180

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false
